#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept

#Eureka的配置，，服务器注册到哪里
eureka:
  client:
    service-url:
      defalutZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


---
#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7001/eureka/